@baseUrl = http://localhost:8080/api

### 201 - Successfully create a user
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "conflict_user_{{$uuid}}",
  "password": "superPassword123"
}

> {%
    client.global.set("conflict_name", response.body.username);

    const runId = response.body.username.substring("conflict_user_".length);

    client.global.set("min_username", runId.substring(0, 3));
    client.global.set(
        "max_username",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" + runId
    );
    client.global.set("min_password_username", "tim1_" + runId);
    client.global.set("max_password_username", "tim2_" + runId);

    client.test("Successfully create a user", function() {
        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        const expected = client.global.get("conflict_name");
        client.assert(body.username === expected, "Server should return name of user");
    });
%}

### 201 - Successfully create a user (with min length user's name)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "{{min_username}}",
  "password": "superPassword123"
}

> {%
    client.test("Successfully create a user", function() {
        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        const expected = client.global.get("min_username");
        client.assert(body.username === expected, "Server should return name of user - username is short");
    });
%}

### 201 - Successfully create a user (with max length user's name)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "{{max_username}}",
  "password": "superPassword123"
}

> {%
    client.test("Successfully create a user", function() {
        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        const expected = client.global.get("max_username");
        client.assert(body.username === expected,
            "Server should return name of user - username is long");
    });
%}

### 201 - Successfully create a user (with min password length)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "{{min_password_username}}",
  "password": "222"
}

> {%
    client.test("Successfully create a user", function() {
        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        const expected = client.global.get("min_password_username");
        client.assert(body.username === expected, "Server should return name of user - password is short");
    });
%}

### 201 - Successfully create a user (with max password length)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "{{max_password_username}}",
  "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

> {%
    client.test("Successfully create a user", function() {
        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        const expected = client.global.get("max_password_username");
        client.assert(body.username === expected, "Server should return name of user - password is long");
    });
%}

### 400 - User name is empty
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "password": "abc123"
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since name is empty ");
    });
%}

### 400 - User name is blank (spaces only)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": " ",
  "password": "abc123"
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since name is blank ");
    });
%}

### 400 - User name is too short
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "aa",
  "password": "abc123"
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since name is too short");
    });
%}

### 400 - Username is too long (over 100 characters)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "password": "aaaa"
}

> {%
    client.test("Cannot create a user since username is too long", function() {
        client.assert(response.status === 400, "Response status is 400 since username is too long");
    });
%}

### 400 - Password is empty
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "tim1",
  "password": ""
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since password is empty ");
    });
%}

### 400 - Password is blank (spaces only)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "tim1",
  "password": " "
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since password is blank ");
    });
%}

### 400 - Password is too short
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "tim1",
  "password": "aa"
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 400, "Response status is 400 since password is too short");
    });
%}

### 400 - Password is too long (over 50 characters)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "tim_too_long",
  "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1"
}

> {%
    client.test("Cannot create a user since password is too long", function() {
        client.assert(response.status === 400, "esponse status is 400 since password is too long");
    });
%}

### 409 - User name is already taken
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "{{conflict_name}}",
  "password": "superPassword123"
}

> {%
    client.test("Cannot create a user", function() {
        client.assert(response.status === 409, "Response status is 409 since user name is already taken");
    });
%}

###