@baseUrlApi = http://localhost:8080/api
@baseUrl = http://localhost:8080

@regUser = timur_auto
@regPass = superPassword123

@test_folder_to_delete = folder1/folder2/folder3/
@test_folder_to = folder9/folder10/

### 401 - Failed to delete a resouese since user wasn't authorized (no cookies provided!)
# @no-cookie-jar
DELETE {{baseUrl}}/resource?path={{test_folder_to_delete}}

> {%
    client.test("Cannot delete resource", function () {
        client.assert(response.status === 401, "Response status is 401 since user is not authorized");
    });
%}

### Prereg (user creation) - method is needed for success test of prelog (1 pre-phase)
POST {{baseUrlApi}}/auth/sign-up
Content-Type: application/json

{
  "username": "timur_auto_{{$uuid}}",
  "password": "{{regPass}}"
}

> {%
    client.global.set("active_user", response.body.username);
    client.global.set("active_pass", "superPassword123");
%}

### Prelog (user authorization) - method is needed for success test of prelog (2 pre-phase)
POST {{baseUrlApi}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "{{active_pass}}"
}

> {%
    client.test("Successfully logged-in", function () {
        client.assert(response.status === 200, "Response status is 200");
        const body = response.body;
        const expected_user = client.global.get("active_user")
        client.assert(body.username === expected_user, "Server should return name of user");
    });

    client.global.set(
        "path_for_upload",
        "gorgon_root/gorgon_archive/gorgon_files_" +
        client.global.get("active_user") +
        "/"
    );
%}

### Successfully uploaded TWO files (picture and text file) to a previosly created folder (3 pre-phase)
# Path to files (passed in query, say, POST {{baseUrl}}/resource?path=folder1/)
POST {{baseUrl}}/resource?path={{path_for_upload}}
Content-Type: multipart/form-data; boundary=boundary

# Part №1 of multipart-File (picture): several file will be converted into files
--boundary
Content-Disposition: form-data; name="file"; filename="gorgon.jpg"
Content-Type: image/jpeg

< ./docs/gorgon.jpg
--boundary
# Part №2 of multipart-File (text file)
Content-Disposition: form-data; name="file"; filename="description_gorgon.txt"
Content-Type: text/plain

< ./docs/description_gorgon.txt
--boundary

> {%
    client.test("Successfully uploaded two files into folder", function () {

        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 2, "Folder should contain exactly 2 resources");

        const expected_parent_path = client.global.get("path_for_upload");

        const firstFile = body.find(item => item.name === "gorgon.jpg");
        //and it's not empty
        client.assert(firstFile !== undefined, "WE have firstFile element in array");
        //hence, we can get some info from this array element (say, array[0]): such as path, name, size and type
        client.assert(firstFile.path === expected_parent_path, "firstFile should have correct parent path");
        client.assert(firstFile.name === "gorgon.jpg", "firstFile name is gorgon.jpg");
        client.assert(typeof firstFile.size === "number" && firstFile.size > 0, "firstFile size field should be > 0");
        client.assert(firstFile.type === "FILE", "firstFile type is file");

        const secondFile = body.find(item => item.name === "description_gorgon.txt");
        client.assert(secondFile !== undefined, "WE have secondFile element in array");
        //hence, we can get some info from this array element (say, array[0]): such as path, name, size and type
        client.assert(secondFile.path === expected_parent_path, "secondFile should have correct parent path");
        client.assert(secondFile.name === "description_gorgon.txt", "secondFile name is description_gorgon.txt");
        client.assert(typeof secondFile.size === "number" && secondFile.size > 0, "secondFile size field should be > 0");
        client.assert(secondFile.type === "FILE", "secondFile type is file");
    });
%}

### Successfully created a folder "unnamed_${active_user}" to a previously created folder "gorgon_archive/" (4 pre-phase)
POST {{baseUrl}}/directory?path=gorgon_root/gorgon_archive/unnamed_{{active_user}}/

> {%
    client.test("Successfully created a folder", function () {
        client.assert(response.status === 201, "Response status is 201");

        const body = response.body;
        const expected_folder_name = "unnamed_" + client.global.get("active_user");

        client.assert(body.path === "gorgon_root/gorgon_archive/", "Folder should have correct parent path");
        client.assert(body.name === expected_folder_name, "Folder should have correct name");
        client.assert(body.type === "DIRECTORY", "Folder type should be DIRECTORY");
    });
    client.global.set(
        "unnamed_folder_path",
        "gorgon_root/gorgon_archive/unnamed_" +
        client.global.get("active_user") +
        "/"
    );
%}

### Successfully uploaded files ("file1.txt", "file2.txt") to new folder (".../different/") (5 pre-phase)
POST {{baseUrl}}/resource?path=gorgon_root/gorgon_archive/gorgon_files_{{active_user}}/different/
Content-Type: multipart/form-data; boundary=boundary

# Part №1
--boundary
Content-Disposition: form-data; name="file"; filename="file1.txt"
Content-Type: text/plain

< ./docs/file1.txt
--boundary

# Part №2
--boundary
Content-Disposition: form-data; name="file"; filename="file2.txt"
Content-Type: text/plain

< ./docs/file2.txt
--boundary--

> {%
    client.test("Successfully uploaded 2 files into folder", function () {
        client.assert(response.status === 201, "Response status is 201");

        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 2, "Response should contain exactly 2 resources");

        const expected_parent_path = "gorgon_root/gorgon_archive/gorgon_files_" + client.global.get("active_user") + "/different/";
        client.global.set("different_folder_path", expected_parent_path);

        const firstFile = body.find(item => item.name === "file1.txt");
        client.assert(firstFile !== undefined, "WE have firstFile element in array");
        client.assert(firstFile.path === expected_parent_path, "firstFile should have correct parent path");
        client.assert(firstFile.name === "file1.txt", "firstFile name is file1.txt");
        client.assert(typeof firstFile.size === "number" && firstFile.size > 0, "firstFile size field should be > 0");
        client.assert(firstFile.type === "FILE", "firstFile type is FILE");

        const secondFile = body.find(item => item.name === "file2.txt");
        client.assert(secondFile !== undefined, "WE have secondFile element in array");
        client.assert(secondFile.path === expected_parent_path, "secondFile should have correct parent path");
        client.assert(secondFile.name === "file2.txt", "secondFile name is file2.txt");
        client.assert(typeof secondFile.size === "number" && secondFile.size > 0, "secondFile size field should be > 0");
        client.assert(secondFile.type === "FILE", "secondFile type is FILE");
    });
%}

### Successfully created EMPTY folder inside gorgon_files_${active_user} (6 pre-phase) -> with preparation pathes for upload for file/folder!
POST {{baseUrl}}/directory?path=gorgon_root/gorgon_archive/gorgon_files_{{active_user}}/empty_folder_{{active_user}}/

# So overall, such scheme fnally:
#
#gorgon_root/
#└── gorgon_archive/ -----------------------------> here to delete WHOLE folder, inluding empty ones (3 deletion)
#    ├── unnamed_${active_user}/
#    └── gorgon_files_${active_user}/
#        ├──empty_folder_${active_user}/ ---------> here to delete an EMPTY folder (2 deletion)
#        ├── gorgon.jpg
#        ├── description_gorgon.txt
#        └── different/
#            ├── file1.txt
#            └── file2.txt -----------------------> here to delete a single FILE (1 deletion)

> {%
    client.test("Successfully created empty folder", function () {
        client.assert(response.status === 201, "Response status is 201");

        const body = response.body;

        const expected_parent_path = "gorgon_root/gorgon_archive/gorgon_files_" + client.global.get("active_user") + "/";

        const expected_folder_name = "empty_folder_" + client.global.get("active_user");

        client.assert(body.path === expected_parent_path, "Folder should have correct parent path");
        client.assert(body.name === expected_folder_name, "Folder should have correct name");
        client.assert(body.type === "DIRECTORY", "Folder type should be DIRECTORY");
    });

    client.global.set(
        "path_for_file_delete",
        "gorgon_root/gorgon_archive/gorgon_files_" +
        client.global.get("active_user") +
        "/different/file2.txt"
    );

    client.global.set(
        "path_for_file_checking_after_delete",
        "gorgon_root/gorgon_archive/gorgon_files_" +
        client.global.get("active_user") +
        "/different/"
    );

    client.global.set(
        "path_for_empty_folder_delete",
        "gorgon_root/gorgon_archive/gorgon_files_" +
        client.global.get("active_user") +
        "/empty_folder_" +
        client.global.get("active_user") +
        "/"
    );

    client.global.set(
        "path_for_whole_folder_delete",
        "gorgon_root/gorgon_archive/"
    );
%}

### 204 - (1) Deleted a single file ("/different/file2.txt")
DELETE  {{baseUrl}}/resource?path={{path_for_file_delete}}

> {%
    client.test("Deleted resource", function () {
        client.assert(response.status === 204, "Response status is 204");
    });
%}

### 200 - (1) Postanalysis - directory contains only file1.txt after file2.txt deletion
GET {{baseUrl}}/directory?path={{path_for_file_checking_after_delete}}

> {%
    client.test("Directory contains one file after deletion", function () {
        client.assert(response.status === 200, "Response status is 200");

        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 1, "Directory should contain exactly 1 resource");

        const expectedPath = client.global.get("path_for_file_checking_after_delete");

        const file1 = body.find(item => item.name === "file1.txt");

        client.assert(file1 !== undefined, "file1.txt should be found");
        client.assert(file1.path === expectedPath, "file1.txt should have correct parent path");
        client.assert(typeof file1.size === "number" && file1.size > 0, "file1.txt size should be > 0");
        client.assert(file1.type === "FILE", "file1.txt type should be FILE");
    });
%}

### 204 - (2) Deleted an empty folder (".../empty_folder_<activeuser>")
DELETE  {{baseUrl}}/resource?path={{path_for_empty_folder_delete}}

> {%
    client.test("Deleted resource", function () {
        client.assert(response.status === 204, "Response status is 204");
    });
%}

### 200 - (2) Postanalysis - searched that provided early directory is deleted now and hence, not found (200)
GET {{baseUrl}}/resource/search?query=empty_folder_{{active_user}}

> {%
    client.test("Search finds nothing (no files, no directories)", function () {
        client.assert(response.status === 200, "Response status is 200");

        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 0, "Search should return exactly 0 resources, since nothing is found");
    });
%}

### 204 - (3) Deleted an whole folder ("gorgon_root/gorgon_archive/")
DELETE  {{baseUrl}}/resource?path={{path_for_whole_folder_delete}}

> {%
    client.test("Deleted resource", function () {
        client.assert(response.status === 204, "Response status is 204");
    });
%}

### 200 - (3) Postanalysis - searched that provided early directory is deleted now and hence, not found (200)
GET {{baseUrl}}/resource/search?query={{path_for_whole_folder_delete}}

> {%
    client.test("Search finds nothing (no files, no directories)", function () {
        client.assert(response.status === 200, "Response status is 200");

        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 0, "Search should return exactly 0 resources, since nothing is found");
    });
%}

### 400 - Failed to delete resource(s) since path is wrong (here = empty)
DELETE  {{baseUrl}}/resource?path=

> {%
    client.test("Cannot delete resources", function () {
        client.assert(response.status === 400, "Response status is 400 since path is wrong");
    });
%}

### 400 - Failed to delete resource(s) since path is wrong  (here = %20%20%20%20)
DELETE  {{baseUrl}}/resource?path==%20%20%20%20

> {%
    client.test("Cannot delete resources", function () {
        client.assert(response.status === 400, "Response status is 400 since path is wrong");
    });
%}

###  400 - Failed to delete resource(s) since path is wrong (here = has invalid symbols)
DELETE {{baseUrl}}/resource?path==№№№/

> {%
    client.test("Cannot delete resources", function () {
        client.assert(response.status === 400, "Response status is 400 since path is wrong");
    });
%}

### 400 -  Failed to delete resource(s) since path is wrong (here = has invalid symbols)
DELETE  {{baseUrl}}/resource?path=abc@

> {%
    client.test("Cannot delete resources", function () {
        client.assert(response.status === 400, "Response status is 400 since path is wrong");
    });
%}

### 400 - Failed to delete resource(s) since path is missing
DELETE  {{baseUrl}}/resource

> {%
    client.test("Cannot delete resources", function () {
        client.assert(response.status === 400, "Response status is 400 since 'path' parameter is missing");
    });
%}

### 404 - Failed to delete resource(s) since resource is not found (here - file)
DELETE  {{baseUrl}}/resource?path={{path_for_file_delete}}_{{active_user}}

> {%
    client.test("Cannot delete resources since resource is not found", function () {
        client.assert(response.status === 404, "Response status is 404");
    });
%}

### 404 - Failed to delete resource(s) since resource is not found (here - folder)
DELETE  {{baseUrl}}/resource?path={{path_for_whole_folder_delete}}_{{active_user}}/

> {%
    client.test("Cannot delete resources since resource is not found", function () {
        client.assert(response.status === 404, "Response status is 404");
    });
%}

###