@baseUrlApi = http://localhost:8080/api
@baseUrl = http://localhost:8080

@regUser = timur_auto
@regPass = superPassword123
@test_file_for_search = gorgon
@test_folder_for_search = folder3/

### 401 - Failed to search a file since user wasn't authorized (no cookies provided!)
# @no-cookie-jar
GET {{baseUrl}}/resource/search?query={{test_file_for_search}}

> {%
    client.test("Cannot find resource", function() {
        client.assert(response.status === 401, "Response status is 401 since user is not authorized");
    });
%}

### Prereg (user creation) - method is needed for success test of prelog (1 pre-phase)
POST {{baseUrlApi}}/auth/sign-up
Content-Type: application/json

{
  "username": "timur_auto_{{$uuid}}",
  "password": "{{regPass}}"
}

> {%
    client.global.set("active_user", response.body.username);
    client.global.set("active_pass", "superPassword123");
%}

### Prelog (user authorization) -  method is needed for success test of prelog (2 pre-phase) - with preparation path for search!
POST {{baseUrlApi}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "{{active_pass}}"
}

> {%
    client.test("Successfully logged-in", function () {
        client.assert(response.status === 200, "Response status is 200");
        const body = response.body;
        const expected_user = client.global.get("active_user")
        client.assert(body.username === expected_user, "Server should return name of user");
    });
    client.global.set(
        "path_for_upload",
        "gorgon_root/gorgon_archive/gorgon_files_" +
        client.global.get("active_user") +
        "/"
    );
%}

### 201 - Successfully uploaded TWO files (picture and text file) to a previosly created folder
# Path to files (passed in query, say, POST {{baseUrl}}/resource?path=folder1/)
POST {{baseUrl}}/resource?path={{path_for_upload}}
Content-Type: multipart/form-data; boundary=boundary

# Part №1 of multipart-File (picture): several file will be converted into files
--boundary
Content-Disposition: form-data; name="file"; filename="gorgon.jpg"
Content-Type: image/jpeg

< ./docs/gorgon.jpg
--boundary
# Part №2 of multipart-File (text file)
Content-Disposition: form-data; name="file"; filename="description_gorgon.txt"
Content-Type: text/plain

< ./docs/description_gorgon.txt
--boundary

#
#        example:
#        [
#            {
#                "path": "gorgon_root/gorgon_archive/gorgon_files_timur_auto_550e8400-e29b-41d4-a716-446655440000/",
#                "name": "gorgon.jpg",
#                "size": 1500,
#                "type": "FILE"
#            },
#            {
#                "path": "gorgon_root/gorgon_archive/gorgon_files_timur_auto_550e8400-e29b-41d4-a716-446655440000/",
#                "name": "description_gorgon.txt",
#                "size": 123,
#                "type": "FILE"
#            }
#        ]

> {%
    client.test("Successfully uploaded two files into folder", function () {

        client.assert(response.status === 201, "Response status is 201");
        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 2, "Folder should contain exactly 2 resources");

        const expected_parent_path = client.global.get("path_for_upload");

        const firstFile = body.find(item => item.name === "gorgon.jpg");
        //and it's not empty
        client.assert(firstFile !== undefined, "WE have firstFile element in array");
        //hence, we can get some info from this array element (say, array[0]): such as path, name, size and type
        client.assert(firstFile.path === expected_parent_path, "firstFile should have correct parent path");
        client.assert(firstFile.name === "gorgon.jpg", "firstFile name is gorgon.jpg");
        client.assert(typeof firstFile.size === "number" && firstFile.size > 0, "firstFile size field should be > 0");
        client.assert(firstFile.type === "FILE", "firstFile type is file");

        const secondFile = body.find(item => item.name === "description_gorgon.txt");
        client.assert(secondFile !== undefined, "WE have secondFile element in array");
        //hence, we can get some info from this array element (say, array[0]): such as path, name, size and type
        client.assert(secondFile.path === expected_parent_path, "secondFile should have correct parent path");
        client.assert(secondFile.name === "description_gorgon.txt", "secondFile name is description_gorgon.txt");
        client.assert(typeof secondFile.size === "number" && secondFile.size > 0, "secondFile size field should be > 0");
        client.assert(secondFile.type === "FILE", "secondFile type is file");
    });
%}

### 200 - Success - searched all files (2) and foldiers (3)
GET {{baseUrl}}/resource/search?query={{test_file_for_search}}

> {%
    client.test("Successfully searched for two files and three folders", function () {
        client.assert(response.status === 200, "Response status is 200");

        const body = response.body;
        client.assert(Array.isArray(body), "Server should return an array");
        client.assert(body.length === 5, "Search should return exactly 5 resources");

        const active_user = client.global.get("active_user");
        const path_for_upload = client.global.get("path_for_upload");

        // gorgon_root/
        const root_folder = body.find(item => item.name === "gorgon_root");
        client.assert(root_folder !== undefined, "gorgon_root should be found");
        client.assert(root_folder.path === "", "gorgon_root should have empty parent path");
        client.assert(root_folder.type === "DIRECTORY", "gorgon_root type is directory");
        client.assert(!("size" in root_folder), "size field should not exist in directory object");

        // gorgon_root/gorgon_archive/
        const archive_folder = body.find(item => item.name === "gorgon_archive");
        client.assert(archive_folder !== undefined, "gorgon_archive should be found");
        client.assert(archive_folder.path === "gorgon_root/", "gorgon_archive should have correct parent path");
        client.assert(archive_folder.type === "DIRECTORY", "gorgon_archive type is directory");
        client.assert(!("size" in archive_folder), "size field should not exist in directory object");

        // gorgon_root/gorgon_archive/gorgon_files_<active_user>/
        const files_folder_name = "gorgon_files_" + active_user;
        const files_folder = body.find(item => item.name === files_folder_name);
        client.assert(files_folder !== undefined, "gorgon_files folder should be found");
        client.assert(
            files_folder.path === "gorgon_root/gorgon_archive/",
            "gorgon_files folder should have correct parent path"
        );
        client.assert(files_folder.type === "DIRECTORY", "gorgon_files type is directory");
        client.assert(!("size" in files_folder), "size field should not exist in directory object");

        // gorgon.jpg
        const firstFile = body.find(item => item.name === "gorgon.jpg");
        client.assert(firstFile !== undefined, "gorgon.jpg should be found");
        client.assert(firstFile.path === path_for_upload, "gorgon.jpg should have correct parent path");
        client.assert(typeof firstFile.size === "number" && firstFile.size > 0, "gorgon.jpg size should be > 0");
        client.assert(firstFile.type === "FILE", "gorgon.jpg type is file");

        // description_gorgon.txt
        const secondFile = body.find(item => item.name === "description_gorgon.txt");
        client.assert(secondFile !== undefined, "description_gorgon.txt should be found");
        client.assert(secondFile.path === path_for_upload, "description_gorgon.txt should have correct parent path");
        client.assert(typeof secondFile.size === "number" && secondFile.size > 0, "description_gorgon.txt size should be > 0");
        client.assert(secondFile.type === "FILE", "description_gorgon.txt type is file");
    });
%}
