@baseUrl = http://localhost:8080/api

@regUser = timur_auto
@regPass = superPassword123

### Prereg (user creation) - method is needed for success test of log-in
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "timur_auto_{{$uuid}}",
  "password": "{{regPass}}"
}

> {%
    client.global.set("active_user", response.body.username);
    client.global.set("active_pass", "superPassword123");
%}

### 200 - Successfully logged-in (success)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "{{active_pass}}"
}

> {%
    client.test("Successfully logged-in", function () {
        client.assert(response.status === 200, "Response status is 200");
        const body = response.body;
        const expected_user = client.global.get("active_user")
        client.assert(body.username === expected_user, "Server should return name of user");
    });
%}

### 400 - Cannot log-in since user name is empty
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "",
  "password": "{{active_pass}}"
}

> {%
    client.test("Cannot log-in since user name is empty", function() {
        client.assert(response.status === 400, "Response status is 400 since name is empty ");
    });
%}

### 400 - Cannot log-in since user name is blank (spaces only)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": " ",
  "password": "{{active_pass}}"
}


> {%
    client.test("Cannot log-in since user name is blank", function() {
        client.assert(response.status === 400, "Response status is 400 since name is blank");
    });
%}

### 400 - Cannot log-in since user name is too short
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "a",
  "password": "{{active_pass}}"
}

> {%
    client.test("Cannot log-in since user name is too short", function() {
        client.assert(response.status === 400, "Response status is 400 since name is too short");
    });
%}

### 400 - Username is too long (over 100 characters)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1",
  "password": "{{active_pass}}"
}

> {%
    client.test("Cannot log-in since username is too long", function() {
        client.assert(response.status === 400, "Response status is 400 since username is too long");
    });
%}

### 400 - Cannot log-in since password is empty
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": ""
}

> {%
    client.test("Cannot log-in since password is empty", function() {
        client.assert(response.status === 400, "Response status is 400 since name is empty ");
    });
%}

### 400 - Password is blank (spaces only)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": " "
}

> {%
    client.test("Cannot log-in password is blank", function() {
        client.assert(response.status === 400, "Response status is 400 since password is blank");
    });
%}

### 400 - Password is too short
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "aa"
}

> {%
    client.test("Cannot log-in password is too short", function() {
        client.assert(response.status === 400, "Response status is 400 since password is too short");
    });
%}

### 400 - Password is too long (over 50 characters)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1"
}

> {%
    client.test("Cannot create a user since password is too long", function() {
        client.assert(response.status === 400, "esponse status is 400 since password is too long");
    });
%}


### 401 - Cannot log-in since password is wrong (username is OK)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "{{active_user}}",
  "password": "wrong_pass"
}

> {%
    client.test("Cannot log-in password is wrong", function() {
        client.assert(response.status === 401, "Response status is 401 since password is wrong");
    });
%}

### 401 - Cannot log-in since username is wrong (password is OK)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "username": "wrong_username",
  "password": "{{active_pass}}"
}

> {%
    client.test("Cannot log-in password is wrong", function() {
        client.assert(response.status === 401, "Response status is 401 since password is wrong");
    });
%}

###